### ISSUE TITLE
MVP, Schema, Sample State Review

### ISSUE THREAD

**Issue by vawhitehouse** [jared-greenberg/airbnsqueeze#1]
# MVP
- Can bookings be edited or canceled?
- Can reviews be edited or deleted?
- #6 - I think this should be Reviews. We need at least one MVP with full CRUD functions and Reviews are a great way to get that in. 

# Schema
+ Update all `created-at`/`updated-at` to snake_case rather than kebab-case
+ Users
  - [x] I think AirBnB also asks for a birthday when signing up, so you'll want to store that
+ Listings
  - [x] Do listings need a title?
+ Reviews
  - [x] Do reviews need a title?

# Sample State
- [x] Users may want to to keep an array of their bookingIds, but you could also achieve this with a a selector in your mapStateToProps so it's your call
- [x] If listings/reviews need titles, you'll want to add them here as well

**Comment by jared-greenberg** [comment]
- Bookings can be canceled. The only way to edit a booking is to delete and rebook, like on Airbnb. 
- Reviews can be both edited and deleted. (I did chose reviews over messaging the host in my initial features)
- Included user's birthday and validated age and I updated created_at/updated_at to snake case in my schema.
- Like Airbnb, listings do have a title, but reviews do not. This change has been update in my sample state.
- Because you only ever need to know the current users's bookings, I handled this with an association in the back end and I used selectors to categorize and sort bookings into past/upcoming.
