### ISSUE TITLE
Backend & Frontend Routes

### ISSUE THREAD

**Issue by vawhitehouse** [jared-greenberg/airbnsqueeze#2]
# Backend Routes
- [x] Will `bookings` need `delete` & `edit` routes?
- [x] `reviews` will need an `edit` route

# Frontend Routes
- [x] What route will users be sent to after making a booking? (I know we can't actually see this on AirBnB but you will need decided where to send them)

**Comment by jared-greenberg** [comment]
I have worked it so that bookings do have delete route. In order to change/edit a booking you must delete and then try to rebook. I know the process on Airbnb works much like this, but is more complicated. 

After a booking is made, I made the decision to bring the user to a page with their upcoming bookings so they have easy access to listing they booked as well as a way to delete their booking.
